set -e
pip install -r requirements.txt
python Neptune_Scikit_learn_regression.py
python Neptune_Scikit_learn_classification.py
python Neptune_Scikit_learn_clustering.py
python Neptune_Scikit_learn_other_options.py
