name: xgboost_time_series_train_conda_env
channels:
  - defaults
dependencies:
  - python=3.9
  - pip=22.3.1
  - pip:
    - neptune
    - neptune-xgboost
    - scikit-learn
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - xgboost
