# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from hooks.py and the example nodes in
# `src/pipelines/`

# Data split parameters
example_test_data_ratio: 0.2

# Random forest parameters
rf_max_depth: 3
rf_max_features: 3
rf_n_estimators: 25

# MLP parameters
mlp_alpha: 0.02
mlp_max_iter: 50