name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.21.2
  - pip=21.2.4
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - pandas>=1.1,<1.2
  - pip:
    - neptune
    - neptune-xgboost
    - neptune-prophet
    - prophet
    - azureml-defaults
    - matplotlib
    - seaborn
    - xgboost
