name: Scheduled scripts tests (ubuntu)
on:
  schedule:
    - cron: "0 0 * * 3" # Run every Wednesday at 12:00 AM UTC
  workflow_dispatch:
jobs:
  test-scripts-ubuntu:
    uses: ./.github/workflows/test-scripts.yml
    with:
      os: ubuntu-latest
  test-docker-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build docker container from Dockerfile
        run: docker build -f how-to-guides/neptune-docker/scripts/Dockerfile --tag neptune-docker .
      - name: run docker container
        run: docker run -e NEPTUNE_API_TOKEN=${{ secrets.ANONYMOUS_API_TOKEN }} neptune-docker
