name: examples-schedules
on:
  schedule:
    - cron: '14 3 1,8,15,22 * *' # Run once a week at arbitrary time (3:14 AM UTC)
  workflow_dispatch:
jobs:
############## NOTEBOOKS ##############
  test-notebooks-ubuntu:
    uses: ./.github/workflows/notebooks.yml
    with:
      os: [ ubuntu-latest ]  
  test-notebooks-windows:
    uses: ./.github/workflows/notebooks.yml
    with:
      os: [ windows-latest ]  
  test-notebooks-macos:
    uses: ./.github/workflows/notebooks.yml
    with:
      os: [ macos-latest ] 
############## SCRIPTS ##############
  test-scripts-ubuntu:
    uses: ./.github/workflows/scripts.yml
    with:
      os: [ ubuntu-latest ] 
  test-scripts-windows:
    uses: ./.github/workflows/scripts.yml
    with:
      os: [ windows-latest ] 
  test-scripts-macos:
    uses: ./.github/workflows/scripts.yml
    with:
      os: [ macos-latest ] 
############## DOCKER ##############
  test-docker-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build docker container from Dockerfile
        run: docker build -f how-to-guides/neptune-docker/scripts/Dockerfile --tag neptune-docker .
      - name: run docker container
        run: docker run -e NEPTUNE_API_TOKEN="ANONYMOUS" neptune-docker
