name: Scheduled notebook tests (macos)
on:
  schedule:
    - cron: "0 0 * * 0" # Run every Sunday at 12:00 AM UTC
  workflow_dispatch:
jobs:
  test-notebooks-macos:
    uses: ./.github/workflows/test-notebooks.yml
    with:
      os: macos-latest
    secrets:
      NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
