name: test-scripts
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      scripts:
        required: true
        type: string
jobs:
  test-scripts:
    runs-on: ${{ inputs.os }}
    timeout-minutes: 300
    strategy:
      fail-fast: false
      matrix:
        os: ${{ inputs.os }}
        python-version: ['3.7', '3.8', '3.9', '3.10']
        scripts: ${{ inputs.scripts }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ inputs.os }}-${{ matrix.python-version }}-pip
          restore-keys: |
            ${{ inputs.os }}-${{ matrix.python-version }}-pip
      - name: Install OpenMP on MacOS for XGBoost integration
        if: runner.os == 'macOS'
        run: brew install libomp
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test examples
        working-directory: ${{ matrix.scripts }}
        run: bash ./run_examples.sh
